reason: initial test

diff --git a/main b/main
--- a/main
+++ b/main
@@ -9,15 +9,17 @@
 # needs mrtrix3 container for eddy_openmp
 #export SINGULARITYENV_OMP_NUM_THREADS=$OMP_NUM_THREADS
 
-time singularity exec -e --nv docker://brainlife/mrtrix3:3.0_RC3 ./topup_eddy.sh
+#time singularity exec -e --nv docker://brainlife/mrtrix3:3.0_RC3 ./topup_eddy.sh
+time singularity exec -e --nv docker://brainlife/mrtrix3:3.0_RC3 ./eddy-bl.sh
 
-time singularity exec -e docker://brainlife/fsl:6.0.1 ./eddy_qc.sh
 
-if [ -s ./dwi/dwi.nii.gz ];
-then
-	echo 0 > finished
-else
-	echo "output missing"
-	echo 1 > finished
-	exit 1
-fi
+#time singularity exec -e docker://brainlife/fsl:6.0.1 ./eddy_qc.sh
+#
+#if [ -s ./dwi/dwi.nii.gz ];
+#then
+#	echo 0 > finished
+#else
+#	echo "output missing"
+#	echo 1 > finished
+#	exit 1
+#fi
