Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -21,11 +21,11 @@ time singularity exec -e --nv docker://brainlife/mrtrix3:3.0.2 ./eddy-bl.sh
 
 #time singularity exec -e docker://brainlife/fsl:6.0.1 ./eddy_qc.sh
 #
-if [ -s ./dwi/dwi.nii.gz ];
-then
-	echo 0 > finished
-else
-	echo "output missing"
-	echo 1 > finished
-	exit 1
-fi
+# if [ -s ./dwi/dwi.nii.gz ];
+# then
+# 	echo 0 > finished
+# else
+# 	echo "output missing"
+# 	echo 1 > finished
+# 	exit 1
+# fi
