Reason: expose topup and eddy params. move to cuda

diff --git a/main b/main
--- a/main
+++ b/main
@@ -4,14 +4,16 @@
 #PBS -l vmem=16gb
 #PBS -V
 
+module load cuda/8.0 #for bridges
+
 # needs mrtrix3 container for eddy_openmp
 time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./topup_eddy.sh
 
-if [ -s ./dwi/dwi.nii.gz ];
-then
-	echo 0 > finished
-else
-	echo "output missing"
-	echo 1 > finished
-	exit 1
-fi
+#if [ -s ./dwi/dwi.nii.gz ];
+#then
+#	echo 0 > finished
+#else
+#	echo "output missing"
+#	echo 1 > finished
+#	exit 1
+#fi
